/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as AlphHackContractJson } from "../AlphHack.ral.json";
import { getContractByCodeHash } from "./contracts";

import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace AlphHackTypes {
  export type Fields = {
    balance: bigint;
  };

  export type State = ContractState<Fields>;

  export type FundedEvent = ContractEvent<{
    initiator: Address;
    amount: bigint;
  }>;

  export interface CallMethodTable {
    fundBalance: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    getUserBal: {
      params: CallContractParams<{ user: Address }>;
      result: CallContractResult<bigint>;
    };
    getBalance: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    fundBalance: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getUserBal: {
      params: SignExecuteContractMethodParams<{ user: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getBalance: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = { users?: Map<Address, bigint> };
}

class Factory extends ContractFactory<AlphHackInstance, AlphHackTypes.Fields> {
  encodeFields(fields: AlphHackTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Funded: 0 };
  consts = { ErrorCodes: { InsufficientAmount: BigInt("0") } };

  at(address: string): AlphHackInstance {
    return new AlphHackInstance(address);
  }

  tests = {
    fundBalance: async (
      params: TestContractParams<
        AlphHackTypes.Fields,
        { amount: bigint },
        AlphHackTypes.Maps
      >
    ): Promise<TestContractResult<null, AlphHackTypes.Maps>> => {
      return testMethod(this, "fundBalance", params, getContractByCodeHash);
    },
    getUserBal: async (
      params: TestContractParams<
        AlphHackTypes.Fields,
        { user: Address },
        AlphHackTypes.Maps
      >
    ): Promise<TestContractResult<bigint, AlphHackTypes.Maps>> => {
      return testMethod(this, "getUserBal", params, getContractByCodeHash);
    },
    getBalance: async (
      params: Omit<
        TestContractParams<AlphHackTypes.Fields, never, AlphHackTypes.Maps>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint, AlphHackTypes.Maps>> => {
      return testMethod(this, "getBalance", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: AlphHackTypes.Fields,
    asset?: Asset,
    address?: string,
    maps?: AlphHackTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const AlphHack = new Factory(
  Contract.fromJson(
    AlphHackContractJson,
    "=6-2+9f=2-2+d9=2-1=1+7=13-1+b=165-1+c=40+7a7e0214696e73657274206174206d617020706174683a2000=192",
    "c8b6fb07ca6edfe5ebd6cfeaab8559e7bd8f0912c1c5787045bd7b85a1f29c4d",
    []
  )
);

// Use this class to interact with the blockchain
export class AlphHackInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    users: new RalphMap<Address, bigint>(
      AlphHack.contract,
      this.contractId,
      "users"
    ),
  };

  async fetchState(): Promise<AlphHackTypes.State> {
    return fetchContractState(AlphHack, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeFundedEvent(
    options: EventSubscribeOptions<AlphHackTypes.FundedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      AlphHack.contract,
      this,
      options,
      "Funded",
      fromCount
    );
  }

  view = {
    fundBalance: async (
      params: AlphHackTypes.CallMethodParams<"fundBalance">
    ): Promise<AlphHackTypes.CallMethodResult<"fundBalance">> => {
      return callMethod(
        AlphHack,
        this,
        "fundBalance",
        params,
        getContractByCodeHash
      );
    },
    getUserBal: async (
      params: AlphHackTypes.CallMethodParams<"getUserBal">
    ): Promise<AlphHackTypes.CallMethodResult<"getUserBal">> => {
      return callMethod(
        AlphHack,
        this,
        "getUserBal",
        params,
        getContractByCodeHash
      );
    },
    getBalance: async (
      params?: AlphHackTypes.CallMethodParams<"getBalance">
    ): Promise<AlphHackTypes.CallMethodResult<"getBalance">> => {
      return callMethod(
        AlphHack,
        this,
        "getBalance",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    fundBalance: async (
      params: AlphHackTypes.SignExecuteMethodParams<"fundBalance">
    ): Promise<AlphHackTypes.SignExecuteMethodResult<"fundBalance">> => {
      return signExecuteMethod(AlphHack, this, "fundBalance", params);
    },
    getUserBal: async (
      params: AlphHackTypes.SignExecuteMethodParams<"getUserBal">
    ): Promise<AlphHackTypes.SignExecuteMethodResult<"getUserBal">> => {
      return signExecuteMethod(AlphHack, this, "getUserBal", params);
    },
    getBalance: async (
      params: AlphHackTypes.SignExecuteMethodParams<"getBalance">
    ): Promise<AlphHackTypes.SignExecuteMethodResult<"getBalance">> => {
      return signExecuteMethod(AlphHack, this, "getBalance", params);
    },
  };

  async multicall<Callss extends AlphHackTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<AlphHackTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      AlphHack,
      this,
      callss,
      getContractByCodeHash
    )) as AlphHackTypes.MulticallReturnType<Callss>;
  }
}
