import React from 'react'
import Head from 'next/head'

export default function Page() {
  return (
    <div>
      <Head>
        <title>AlphHack - Create</title>
        <meta name="description" content="Generated by @alephium/cli init" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-gray-300 font-light">
        <div className="w-11/12 md:w-2/5 h-7/12 p-6 mx-auto">
          <form className="flex flex-col">
            <div className="flex flex-col justify-center items-center rounded-xl mt-5 mb-5">
              <h4 className="text-lg">Create Proposal</h4>
              <p className='text-sm'>A proposal cost 4 ALPH tokens, voting is free!</p>
            </div>
            <div
              className="flex flex-row justify-between items-center bg-gray-300 bg-opacity-10
              rounded-xl mt-5 p-2"
            >
              <input
                className="block w-full text-sm text-slate-500 bg-transparent border-0
                focus:outline-none focus:ring-0"
                type="text"
                name="title"
                placeholder="Proposal title"
              />
            </div>
            <div
              className="flex flex-row justify-between items-center bg-gray-300 bg-opacity-10
              rounded-xl mt-5 p-2"
            >
              <textarea
                className="block w-full text-sm resize-none text-slate-500 bg-transparent
                border-0 focus:outline-none focus:ring-0 h-20"
                name="question"
                placeholder="Proposal detail..."
              />
            </div>
            <button className="bg-blue-500 shadow-sm hover:shadow-blue-900 text-white
            rounded-full p-2 min-w-28 text-md md:block hover:bg-[#141f34]
            transition duration-300 ease-in-out transform hover:scale-105 block mt-5">
              Submit
            </button>
          </form>
        </div>
      </div>
    </div>
  )
}
