import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import butterfly from '../../assets/butterfly.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alph Hack</title>
        <meta name="description" content="Generated by @alephium/cli init" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="game" className="w-full h-80 border-gray-700 border mx-auto">
        <div
          id="dino"
          className="bg-no-repeat w-16 h-16 absolute top-52 bg-cover bg-center"
          style={{ backgroundImage: `url(${butterfly.src})` }}
        />
        <div id="cactus"></div>
      </div>

      <div className="flex justify-center items-center mt-8">
        <button className="bg-red-500 text-white rounded-full p-1 min-w-28 text-md hidden md:block">Jump</button>
      </div>
    </div>
  )
}
